language: node_js
node_js:
- '0.10'
before_install:
- openssl aes-256-cbc -K $encrypted_61fa163ff908_key -iv $encrypted_61fa163ff908_iv
  -in ssh-private-key.enc -out ssh-private-key -d
install:
- git config --global user.email "bpsayers@gmail.com"
- git config --global user.name "Ben Sayers"
- echo -e "Host bitbucket.org\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- chmod 600 ssh-private-key
- eval `ssh-agent -s`
- ssh-add ssh-private-key
- npm install -g grunt-cli
- npm install -g bower
- npm install
- bower install
env:
  global:
  - secure: Ry6nDGiRvDObClXXeQcGq23eaGjitnMizsltLw7gWBswc+qWXoZEVRbL/dzsLV24Q3Zq9KDnXPWfrQuf7vM23roKcl5QELP//+BpiibxmE8UT6sHlq0B9/AE5X5iqhp7Oni3s6rJqDzr27QLcUWZ6ZrDcMYD+8WiUyHVU06BhP4=
  - secure: Q/gxjodWscOvTgDUWeRB4HGQnTLGAitclk/LlENzplBJ1KyfJk/busrsl/5yGa7sMyOt2AFhC+prrdPE05bmH2hADdEUEZ/TRtz/y6BVzvNzRotoRAML7gqg4gxMyOt+JNZD6ux7q/W//pM+xh7hhcYMpKRO0fWw6JTJcrKT1Bw=
